# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x1a\x1bgoogle/protobuf/empty.proto\"[\n\x0eRoundModelInfo\x12\x14\n\x0cround_number\x18\x01 \x01(\x03\x12\x19\n\x11weights_file_name\x18\x02 \x01(\t\x12\x18\n\x10selected_clients\x18\x03 \x03(\x03\"\xdb\x01\n\x0cUpdateResult\x12\x0b\n\x03\x63id\x18\x01 \x01(\x03\x12\x14\n\x0cround_number\x18\x02 \x01(\x03\x12\x1a\n\x12local_round_number\x18\x03 \x01(\x03\x12\x0f\n\x07weights\x18\x04 \x01(\t\x12\x12\n\ntrain_size\x18\x05 \x01(\x03\x12\x12\n\ntrain_loss\x18\x06 \x01(\x01\x12\x1c\n\x14time_receive_request\x18\x07 \x01(\x02\x12\x19\n\x11time_start_update\x18\x08 \x01(\x02\x12\x1a\n\x12time_finish_update\x18\t \x01(\x02\"\xbc\x01\n\x10\x45valuationResult\x12\x0b\n\x03\x63id\x18\x01 \x01(\x03\x12\x14\n\x0cround_number\x18\x02 \x01(\x03\x12\x1a\n\x12local_round_number\x18\x03 \x01(\x03\x12\x1c\n\x14time_receive_request\x18\x04 \x01(\x02\x12\x1b\n\x13time_start_evaluate\x18\x05 \x01(\x02\x12\x1c\n\x14time_finish_evaluate\x18\x06 \x01(\x02\x12\x10\n\x08\x65valuate\x18\x07 \x01(\t\"8\n\x0cRegistration\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\x03\x12\x12\n\nclient_ids\x18\x02 \x03(\x03\"\x80\x02\n\x0fProtocolMessage\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12%\n\x0cregistration\x18\x02 \x01(\x0b\x32\r.RegistrationH\x00\x12+\n\x10round_model_info\x18\x03 \x01(\x0b\x32\x0f.RoundModelInfoH\x00\x12&\n\rupdate_result\x18\x04 \x01(\x0b\x32\r.UpdateResultH\x00\x12.\n\x11\x65valuation_result\x18\x05 \x01(\x0b\x32\x11.EvaluationResultH\x00\x12\'\n\x05\x65mpty\x18\x06 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\t\n\x07payload2H\n\x11\x46\x65\x64\x65ratedLearning\x12\x33\n\x07\x63onnect\x12\x10.ProtocolMessage\x1a\x10.ProtocolMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROUNDMODELINFO._serialized_start=43
  _ROUNDMODELINFO._serialized_end=134
  _UPDATERESULT._serialized_start=137
  _UPDATERESULT._serialized_end=356
  _EVALUATIONRESULT._serialized_start=359
  _EVALUATIONRESULT._serialized_end=547
  _REGISTRATION._serialized_start=549
  _REGISTRATION._serialized_end=605
  _PROTOCOLMESSAGE._serialized_start=608
  _PROTOCOLMESSAGE._serialized_end=864
  _FEDERATEDLEARNING._serialized_start=866
  _FEDERATEDLEARNING._serialized_end=938
# @@protoc_insertion_point(module_scope)
