FedModel:
  name: FedAvg
  # Shared params
  B: 32 # batch size
  C: 0.4 # ratio of clients performing computation in each round
  E: 5 # epochs 
  distributed_evaluate: false
  evaluate_ratio: 1.0
  max_rounds: 10

  num_tolerance: 100
  rounds_between_val: 1
  # FedSTC
  sparsity: 0.01
  # FedProx
  mu: 0.01
  # FedOpt
  tau: 0.0001
  beta1: 0.9
  beta2: 0.99
  opt_name: 'fedyogi'
  # Server LR, used by FedOpt and FedSCA
  eta: 1.0
MLModel:
  name: crude_CNN
  activation: relu
  dropout: 0.2
  threshold: 0
  units:
    - 512
    - 512
  optimizer:
    name: adam
    lr: 0.001
    momentum: 0
  loss: categorical_crossentropy
  metrics:
    - accuracy
