docker:
  image: fedeval:v2
  num_containers: 2
  enable_gpu: false
  num_gpu: 0
server:
  host: server
  listen: server
  num_clients: 10
  port: 8000
  secret_key: secret!
log:
  log_dir: log/crudeCNN
  base_level: INFO
  file_log_level: INFO
  console_log_level: INFO
communication:
  method: SocketIO
  port: 8001
  limit_network_resource: false
  bandwidth_upload: 10Mbit
  bandwidth_download: 30Mbit
  latency: 50ms
  fast_mode: true
